spring:
  server:
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      mode: HTML5
      property: name="concurrent" value="false"
  datasource:
    local:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/pf?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
server:
  port: 80
  jetty:
    max-http-response-header-size: 65536
### SSL 設定，使用keystore.p12
#server:
#  port: 8081
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.p12
#    key-store-password: 123456
#    key-password: 123456
#    key-store-type: PKCS12
#    protocol: TLS
#    enabled-protocols: TLSv1.2

### 自定義參數寫死區，無存取資料庫的資料
public:
  # Bacnet -> 本地虛擬設備參數[本機IP/子網路遮罩/port/虛擬本機ID(隨意)]
  bacnet:
    local-ip: 192.168.1.200
    subnet: 255.255.255.0
    port: 47808
    device-id: 123456
  discord:
    token: myToken
    channel-id: id